import { useState, useEffect, useRef } from "react";
import Head from "next/head";
import Link from "next/link";

const T = {
  en: {dir:"ltr",cta_lang:"EN",badge:"🌍 Digital Time Capsule · Opens January 1, 2036",hero1:"One message.",hero2:"One dollar.",hero3:"Forever.",sub:"Write your message to the world. It will be sealed until January 1, 2036 — then revealed to everyone, everywhere, forever.",counter_msgs:"messages sealed",counter_countries:"countries",counter_raised:"raised so far",cta:"Leave My Message — $1",cta_sub:"Secure payment · 60 seconds · Join history",story_badge:"WHY THIS EXISTS",story_title:"A snapshot of humanity, sealed in time.",story_p1:"In 2026, we asked a simple question: if you could say one thing to the entire world — and know it would be read in 10 years — what would you say?",story_p2:"OneMessage.world is not a product. It's a permanent record. Every person who pays $1 becomes part of a living archive of human thought, hope, fear, and love — exactly as it existed in 2026.",story_p3:"When the capsule opens on January 1, 2036, every message will be published for free, forever. The world will read what humanity was thinking today.",story_quote:"\"Future generations will look back at this capsule the way we look at time capsules buried in 1926.\"",form_title:"Write your message to 2036",form_name:"Your name (optional)",form_country:"Your country",form_msg:"Your message to the future...",form_vis:"My message is",form_public:"Public — visible in 2036",form_private:"Private — sealed until 2036",form_chars:"characters remaining",form_submit:"Seal My Message — $1",form_note:"Your message is encrypted and stored permanently. If this site ever closes, all messages will be published publicly for free.",live_title:"Live — Messages Being Sealed Right Now",why_title:"Why will you regret not doing this?",why1_t:"You existed.",why1_d:"In 2036, someone will read your words and know you were here — thinking, feeling, alive in 2026.",why2_t:"Less than a coffee.",why2_d:"One dollar. You've spent more on things you've already forgotten.",why3_t:"The counter never resets.",why3_d:"Every person who pays joins a permanent record. The number only goes up. Be early.",cd_title:"Capsule opens in",days:"Days",hours:"Hours",mins:"Minutes",secs:"Seconds",trust1:"256-bit encrypted",trust2:"Stripe secured",trust3:"Permanently hosted",transparency:"Full Transparency",modal_title:"Your message is almost sealed 🔒",modal_body:"Complete your $1 payment to permanently lock your message until 2036.",modal_pay:"Pay $1 with Stripe →",modal_cancel:"Maybe later",success_title:"You're now part of history ✨",success_sub:"Your message is sealed. Come back January 1, 2036.",success_share:"Share and inspire others to leave their mark:",share_tw:"Share on X",share_wa:"Share on WhatsApp",share_fb:"Share on Facebook",share_copy:"Copy Link",copied:"Copied!",footer:"© 2026 OneMessage.world · A permanent record of humanity"},
  ar: {dir:"rtl",cta_lang:"AR",badge:"🌍 كبسولة زمنية رقمية · تُفتح في 1 يناير 2036",hero1:"رسالة واحدة.",hero2:"دولار واحد.",hero3:"للأبد.",sub:"اكتب رسالتك للعالم. ستُحفظ حتى الأول من يناير 2036 — ثم تُكشف للجميع، في كل مكان، للأبد.",counter_msgs:"رسالة مختومة",counter_countries:"دولة",counter_raised:"جُمع حتى الآن",cta:"اترك رسالتي — دولار واحد",cta_sub:"دفع آمن · 60 ثانية · كن جزءاً من التاريخ",story_badge:"لماذا وُجد هذا",story_title:"لقطة من الإنسانية، محفوظة في الزمن.",story_p1:"في عام 2026، طرحنا سؤالاً بسيطاً: لو كان بإمكانك قول شيء واحد للعالم كله — وتعلم أنه سيُقرأ بعد 10 سنوات — ماذا ستقول؟",story_p2:"OneMessage.world ليس منتجاً. إنه سجل دائم. كل من يدفع دولاراً يصبح جزءاً من أرشيف حيّ للفكر الإنساني والأمل والخوف والحب — كما كان في 2026.",story_p3:"عندما تُفتح الكبسولة في الأول من يناير 2036، ستُنشر كل رسالة مجاناً للأبد.",story_quote:"\"ستنظر الأجيال القادمة إلى هذه الكبسولة كما ننظر نحن إلى كبسولات دُفنت عام 1926.\"",form_title:"اكتب رسالتك إلى 2036",form_name:"اسمك (اختياري)",form_country:"بلدك",form_msg:"رسالتك إلى المستقبل...",form_vis:"رسالتي",form_public:"عامة — تظهر في 2036",form_private:"سرية — مختومة حتى 2036",form_chars:"حرف متبقٍّ",form_submit:"اختم رسالتي — دولار واحد",form_note:"رسالتك مشفّرة ومحفوظة للأبد. إذا أُغلق الموقع، ستُنشر كل الرسائل مجاناً.",live_title:"مباشر — رسائل تُختم الآن",why_title:"لماذا ستندم إن لم تفعل؟",why1_t:"كنتَ هنا.",why1_d:"في 2036، سيقرأ أحدهم كلماتك ويعلم أنك كنت هنا — تفكر، تشعر، حياً في 2026.",why2_t:"أقل من ثمن قهوة.",why2_d:"دولار واحد. أنفقتَ أكثر على أشياء نسيتها بالفعل.",why3_t:"العداد لا يُعاد أبداً.",why3_d:"كل من يدفع يصبح جزءاً من سجل دائم. الرقم يرتفع فقط. كن من الأوائل.",cd_title:"الكبسولة تُفتح بعد",days:"يوم",hours:"ساعة",mins:"دقيقة",secs:"ثانية",trust1:"تشفير 256-bit",trust2:"دفع آمن Stripe",trust3:"استضافة دائمة",transparency:"شفافية كاملة",modal_title:"رسالتك على وشك الاختتام 🔒",modal_body:"أكمل دفع الدولار الواحد لتُختم رسالتك نهائياً حتى 2036.",modal_pay:"ادفع $1 عبر Stripe →",modal_cancel:"ربما لاحقاً",success_title:"أصبحتَ جزءاً من التاريخ ✨",success_sub:"رسالتك مختومة. عُد في الأول من يناير 2036.",success_share:"شارك وألهم الآخرين لتركِ بصمتهم:",share_tw:"شارك على X",share_wa:"شارك على واتساب",share_fb:"شارك على فيسبوك",share_copy:"انسخ الرابط",copied:"تم النسخ!",footer:"© 2026 OneMessage.world · سجل دائم للإنسانية"},
  pt: {dir:"ltr",cta_lang:"PT",badge:"🌍 Cápsula do Tempo Digital · Abre em 1 de janeiro de 2036",hero1:"Uma mensagem.",hero2:"Um dólar.",hero3:"Para sempre.",sub:"Escreva sua mensagem para o mundo. Ficará guardada até 1º de janeiro de 2036 — depois revelada a todos, em todo lugar, para sempre.",counter_msgs:"mensagens seladas",counter_countries:"países",counter_raised:"arrecadado",cta:"Deixar Minha Mensagem — $1",cta_sub:"Pagamento seguro · 60 segundos · Faça parte da história",story_badge:"POR QUE ISSO EXISTE",story_title:"Um retrato da humanidade, selado no tempo.",story_p1:"Em 2026, fizemos uma pergunta simples: se você pudesse dizer uma coisa para o mundo inteiro — e soubesse que seria lida em 10 anos — o que diria?",story_p2:"OneMessage.world não é um produto. É um registro permanente. Cada pessoa que paga $1 se torna parte de um arquivo vivo do pensamento, esperança e amor humano — exatamente como era em 2026.",story_p3:"Quando a cápsula abrir em 1º de janeiro de 2036, cada mensagem será publicada gratuitamente, para sempre.",story_quote:"\"As gerações futuras olharão para esta cápsula como olhamos para as enterradas em 1926.\"",form_title:"Escreva sua mensagem para 2036",form_name:"Seu nome (opcional)",form_country:"Seu país",form_msg:"Sua mensagem para o futuro...",form_vis:"Minha mensagem é",form_public:"Pública — visível em 2036",form_private:"Privada — selada até 2036",form_chars:"caracteres restantes",form_submit:"Selar Minha Mensagem — $1",form_note:"Sua mensagem é criptografada e armazenada permanentemente.",live_title:"Ao Vivo — Mensagens sendo seladas agora",why_title:"Por que você vai se arrepender?",why1_t:"Você existiu.",why1_d:"Em 2036, alguém lerá suas palavras e saberá que você estava aqui, vivo em 2026.",why2_t:"Menos que um café.",why2_d:"Um dólar. Você já gastou mais em coisas que esqueceu.",why3_t:"O contador nunca zera.",why3_d:"Cada pessoa que paga entra num registro permanente.",cd_title:"A cápsula abre em",days:"Dias",hours:"Horas",mins:"Minutos",secs:"Segundos",trust1:"Criptografia 256-bit",trust2:"Pagamento Stripe",trust3:"Hospedado para sempre",transparency:"Transparência Total",modal_title:"Sua mensagem está quase selada 🔒",modal_body:"Complete o pagamento de $1 para selar sua mensagem permanentemente até 2036.",modal_pay:"Pagar $1 com Stripe →",modal_cancel:"Talvez depois",success_title:"Você agora faz parte da história ✨",success_sub:"Sua mensagem está selada. Volte em 1º de janeiro de 2036.",success_share:"Compartilhe e inspire outros:",share_tw:"Compartilhar no X",share_wa:"Compartilhar no WhatsApp",share_fb:"Compartilhar no Facebook",share_copy:"Copiar Link",copied:"Copiado!",footer:"© 2026 OneMessage.world · Um registro permanente da humanidade"},
  es: {dir:"ltr",cta_lang:"ES",badge:"🌍 Cápsula del Tiempo Digital · Abre el 1 de enero de 2036",hero1:"Un mensaje.",hero2:"Un dólar.",hero3:"Para siempre.",sub:"Escribe tu mensaje para el mundo. Quedará sellado hasta el 1 de enero de 2036 — luego revelado a todos, en todo lugar, para siempre.",counter_msgs:"mensajes sellados",counter_countries:"países",counter_raised:"recaudado",cta:"Dejar Mi Mensaje — $1",cta_sub:"Pago seguro · 60 segundos · Sé parte de la historia",story_badge:"POR QUÉ EXISTE ESTO",story_title:"Una instantánea de la humanidad, sellada en el tiempo.",story_p1:"En 2026, hicimos una pregunta simple: si pudieras decirle una cosa al mundo entero — y supieras que sería leída en 10 años — ¿qué dirías?",story_p2:"OneMessage.world no es un producto. Es un registro permanente. Cada persona que paga $1 se convierte en parte de un archivo vivo del pensamiento, esperanza y amor humano.",story_p3:"Cuando la cápsula se abra el 1 de enero de 2036, cada mensaje se publicará gratis, para siempre.",story_quote:"\"Las generaciones futuras mirarán esta cápsula como miramos las enterradas en 1926.\"",form_title:"Escribe tu mensaje para 2036",form_name:"Tu nombre (opcional)",form_country:"Tu país",form_msg:"Tu mensaje al futuro...",form_vis:"Mi mensaje es",form_public:"Público — visible en 2036",form_private:"Privado — sellado hasta 2036",form_chars:"caracteres restantes",form_submit:"Sellar Mi Mensaje — $1",form_note:"Tu mensaje está cifrado y almacenado permanentemente.",live_title:"En Vivo — Mensajes siendo sellados ahora",why_title:"¿Por qué te arrepentirás?",why1_t:"Exististe.",why1_d:"En 2036, alguien leerá tus palabras y sabrá que estuviste aquí, vivo en 2026.",why2_t:"Menos que un café.",why2_d:"Un dólar. Has gastado más en cosas que ya olvidaste.",why3_t:"El contador nunca se reinicia.",why3_d:"Cada persona que paga entra en un registro permanente.",cd_title:"La cápsula se abre en",days:"Días",hours:"Horas",mins:"Minutos",secs:"Segundos",trust1:"Cifrado 256-bit",trust2:"Pago Stripe",trust3:"Alojado para siempre",transparency:"Transparencia Total",modal_title:"Tu mensaje está casi sellado 🔒",modal_body:"Completa el pago de $1 para sellar tu mensaje permanentemente hasta 2036.",modal_pay:"Pagar $1 con Stripe →",modal_cancel:"Quizás después",success_title:"Ahora eres parte de la historia ✨",success_sub:"Tu mensaje está sellado. Vuelve el 1 de enero de 2036.",success_share:"Comparte e inspira a otros:",share_tw:"Compartir en X",share_wa:"Compartir en WhatsApp",share_fb:"Compartir en Facebook",share_copy:"Copiar Enlace",copied:"¡Copiado!",footer:"© 2026 OneMessage.world · Un registro permanente de la humanidad"},
  fr: {dir:"ltr",cta_lang:"FR",badge:"🌍 Capsule Temporelle Digitale · S'ouvre le 1er janvier 2036",hero1:"Un message.",hero2:"Un dollar.",hero3:"Pour toujours.",sub:"Écrivez votre message pour le monde. Il sera scellé jusqu'au 1er janvier 2036 — puis révélé à tous, partout, pour toujours.",counter_msgs:"messages scellés",counter_countries:"pays",counter_raised:"collectés",cta:"Laisser Mon Message — 1$",cta_sub:"Paiement sécurisé · 60 secondes · Entrez dans l'histoire",story_badge:"POURQUOI CELA EXISTE",story_title:"Un instantané de l'humanité, scellé dans le temps.",story_p1:"En 2026, nous avons posé une question simple : si vous pouviez dire une chose au monde entier — et savoir qu'elle serait lue dans 10 ans — que diriez-vous ?",story_p2:"OneMessage.world n'est pas un produit. C'est un registre permanent. Chaque personne qui paie 1$ fait partie d'une archive vivante de la pensée, de l'espoir et de l'amour humain.",story_p3:"Quand la capsule s'ouvrira le 1er janvier 2036, chaque message sera publié gratuitement, pour toujours.",story_quote:"\"Les générations futures regarderont cette capsule comme nous regardons celles enterrées en 1926.\"",form_title:"Écrivez votre message pour 2036",form_name:"Votre nom (optionnel)",form_country:"Votre pays",form_msg:"Votre message pour le futur...",form_vis:"Mon message est",form_public:"Public — visible en 2036",form_private:"Privé — scellé jusqu'en 2036",form_chars:"caractères restants",form_submit:"Sceller Mon Message — 1$",form_note:"Votre message est chiffré et stocké en permanence.",live_title:"En Direct — Messages scellés maintenant",why_title:"Pourquoi regretterez-vous de ne pas l'avoir fait ?",why1_t:"Vous avez existé.",why1_d:"En 2036, quelqu'un lira vos mots et saura que vous étiez là, vivant en 2026.",why2_t:"Moins cher qu'un café.",why2_d:"Un dollar. Vous avez dépensé plus pour des choses déjà oubliées.",why3_t:"Le compteur ne se réinitialise jamais.",why3_d:"Chaque personne rejoint un registre permanent.",cd_title:"La capsule s'ouvre dans",days:"Jours",hours:"Heures",mins:"Minutes",secs:"Secondes",trust1:"Chiffrement 256-bit",trust2:"Paiement Stripe",trust3:"Hébergé définitivement",transparency:"Transparence Totale",modal_title:"Votre message est presque scellé 🔒",modal_body:"Complétez le paiement d'1$ pour sceller définitivement votre message jusqu'en 2036.",modal_pay:"Payer 1$ avec Stripe →",modal_cancel:"Peut-être plus tard",success_title:"Vous faites maintenant partie de l'histoire ✨",success_sub:"Votre message est scellé. Revenez le 1er janvier 2036.",success_share:"Partagez et inspirez les autres :",share_tw:"Partager sur X",share_wa:"Partager sur WhatsApp",share_fb:"Partager sur Facebook",share_copy:"Copier le lien",copied:"Copié !",footer:"© 2026 OneMessage.world · Un registre permanent de l'humanité"},
  de: {dir:"ltr",cta_lang:"DE",badge:"🌍 Digitale Zeitkapsel · Öffnet am 1. Januar 2036",hero1:"Eine Nachricht.",hero2:"Ein Dollar.",hero3:"Für immer.",sub:"Schreibe deine Nachricht für die Welt. Sie wird bis zum 1. Januar 2036 versiegelt — dann für alle, überall, für immer enthüllt.",counter_msgs:"Nachrichten versiegelt",counter_countries:"Länder",counter_raised:"gesammelt",cta:"Meine Nachricht hinterlassen — 1$",cta_sub:"Sichere Zahlung · 60 Sekunden · Teil der Geschichte werden",story_badge:"WARUM ES DAS GIBT",story_title:"Ein Schnappschuss der Menschheit, in der Zeit versiegelt.",story_p1:"Im Jahr 2026 stellten wir eine einfache Frage: Was würdest du der ganzen Welt sagen — wenn du wüsstest, dass es in 10 Jahren gelesen wird?",story_p2:"OneMessage.world ist kein Produkt. Es ist ein dauerhaftes Register. Jeder, der 1$ zahlt, wird Teil eines lebendigen Archivs menschlichen Denkens und Fühlens aus dem Jahr 2026.",story_p3:"Wenn die Kapsel am 1. Januar 2036 geöffnet wird, wird jede Nachricht kostenlos und für immer veröffentlicht.",story_quote:"\"Zukünftige Generationen werden auf diese Kapsel blicken wie wir auf die von 1926.\"",form_title:"Schreibe deine Nachricht für 2036",form_name:"Dein Name (optional)",form_country:"Dein Land",form_msg:"Deine Nachricht an die Zukunft...",form_vis:"Meine Nachricht ist",form_public:"Öffentlich — sichtbar in 2036",form_private:"Privat — versiegelt bis 2036",form_chars:"Zeichen verbleibend",form_submit:"Meine Nachricht versiegeln — 1$",form_note:"Deine Nachricht wird verschlüsselt und dauerhaft gespeichert.",live_title:"Live — Nachrichten werden jetzt versiegelt",why_title:"Warum wirst du es bereuen?",why1_t:"Du hast existiert.",why1_d:"2036 wird jemand deine Worte lesen und wissen, dass du hier warst — lebendig in 2026.",why2_t:"Weniger als ein Kaffee.",why2_d:"Ein Dollar. Du hast mehr für Dinge ausgegeben, die du längst vergessen hast.",why3_t:"Der Zähler wird nie zurückgesetzt.",why3_d:"Jeder, der zahlt, wird Teil eines dauerhaften Registers.",cd_title:"Die Kapsel öffnet in",days:"Tage",hours:"Stunden",mins:"Minuten",secs:"Sekunden",trust1:"256-Bit-Verschlüsselung",trust2:"Stripe-Zahlung",trust3:"Dauerhaft gehostet",transparency:"Volle Transparenz",modal_title:"Deine Nachricht ist fast versiegelt 🔒",modal_body:"Schließe die Zahlung von 1$ ab, um deine Nachricht bis 2036 dauerhaft zu versiegeln.",modal_pay:"1$ mit Stripe bezahlen →",modal_cancel:"Vielleicht später",success_title:"Du bist jetzt Teil der Geschichte ✨",success_sub:"Deine Nachricht ist versiegelt. Komm am 1. Januar 2036 zurück.",success_share:"Teile und inspiriere andere:",share_tw:"Auf X teilen",share_wa:"Auf WhatsApp teilen",share_fb:"Auf Facebook teilen",share_copy:"Link kopieren",copied:"Kopiert!",footer:"© 2026 OneMessage.world · Ein dauerhaftes Register der Menschheit"},
  it: {dir:"ltr",cta_lang:"IT",badge:"🌍 Capsula del Tempo Digitale · Si apre l'1 gennaio 2036",hero1:"Un messaggio.",hero2:"Un dollaro.",hero3:"Per sempre.",sub:"Scrivi il tuo messaggio per il mondo. Sarà sigillato fino all'1 gennaio 2036 — poi rivelato a tutti, ovunque, per sempre.",counter_msgs:"messaggi sigillati",counter_countries:"paesi",counter_raised:"raccolti",cta:"Lascia Il Mio Messaggio — $1",cta_sub:"Pagamento sicuro · 60 secondi · Entra nella storia",story_badge:"PERCHÉ ESISTE",story_title:"Un'istantanea dell'umanità, sigillata nel tempo.",story_p1:"Nel 2026, ci siamo posti una domanda semplice: cosa diresti al mondo intero — sapendo che verrebbe letto tra 10 anni?",story_p2:"OneMessage.world non è un prodotto. È un registro permanente dell'umanità esattamente come era nel 2026.",story_p3:"Quando la capsula si aprirà il 1° gennaio 2036, ogni messaggio sarà pubblicato gratuitamente, per sempre.",story_quote:"\"Le generazioni future guarderanno questa capsula come noi guardiamo quelle sepolte nel 1926.\"",form_title:"Scrivi il tuo messaggio per il 2036",form_name:"Il tuo nome (opzionale)",form_country:"Il tuo paese",form_msg:"Il tuo messaggio al futuro...",form_vis:"Il mio messaggio è",form_public:"Pubblico — visibile nel 2036",form_private:"Privato — sigillato fino al 2036",form_chars:"caratteri rimanenti",form_submit:"Sigilla Il Mio Messaggio — $1",form_note:"Il tuo messaggio è crittografato e conservato permanentemente.",live_title:"In Diretta — Messaggi sigillati adesso",why_title:"Perché te ne pentirai?",why1_t:"Sei esistito.",why1_d:"Nel 2036, qualcuno leggerà le tue parole e saprà che eri qui, vivo nel 2026.",why2_t:"Meno di un caffè.",why2_d:"Un dollaro. Hai speso di più per cose già dimenticate.",why3_t:"Il contatore non si azzera mai.",why3_d:"Ogni persona entra in un registro permanente.",cd_title:"La capsula si apre tra",days:"Giorni",hours:"Ore",mins:"Minuti",secs:"Secondi",trust1:"Crittografia 256-bit",trust2:"Pagamento Stripe",trust3:"Ospitato per sempre",transparency:"Piena Trasparenza",modal_title:"Il tuo messaggio è quasi sigillato 🔒",modal_body:"Completa il pagamento di $1 per sigillare permanentemente il tuo messaggio fino al 2036.",modal_pay:"Paga $1 con Stripe →",modal_cancel:"Forse dopo",success_title:"Ora fai parte della storia ✨",success_sub:"Il tuo messaggio è sigillato. Torna il 1° gennaio 2036.",success_share:"Condividi e ispira gli altri:",share_tw:"Condividi su X",share_wa:"Condividi su WhatsApp",share_fb:"Condividi su Facebook",share_copy:"Copia Link",copied:"Copiato!",footer:"© 2026 OneMessage.world · Un registro permanente dell'umanità"},
  ja: {dir:"ltr",cta_lang:"JA",badge:"🌍 デジタルタイムカプセル · 2036年1月1日開封",hero1:"一つのメッセージ。",hero2:"一ドル。",hero3:"永遠に。",sub:"世界へのメッセージを書いてください。2036年1月1日まで封印され、その日に世界中の全員に公開されます。",counter_msgs:"件封印済み",counter_countries:"カ国",counter_raised:"集まった金額",cta:"メッセージを残す — $1",cta_sub:"安全な決済 · 60秒 · 歴史の一部になろう",story_badge:"なぜこれが存在するのか",story_title:"時間の中に封印された人類のスナップショット。",story_p1:"2026年、私たちはシンプルな問いを立てました。もし世界全体に一つのことを伝えられるなら、そして10年後に読まれると知っていたなら、何を言いますか？",story_p2:"OneMessage.worldは製品ではありません。永久的な記録です。$1を支払うすべての人が、2026年の人類の思想・希望・恐れ・愛の生きたアーカイブの一部になります。",story_p3:"2036年1月1日にカプセルが開封されると、すべてのメッセージが永久に無料公開されます。",story_quote:"「未来の世代は、1926年に埋められたタイムカプセルを見るようにこのカプセルを見るでしょう。」",form_title:"2036年へのメッセージを書く",form_name:"お名前（任意）",form_country:"お住まいの国",form_msg:"未来へのメッセージ...",form_vis:"メッセージの公開設定",form_public:"公開 — 2036年に表示",form_private:"非公開 — 2036年まで封印",form_chars:"文字残り",form_submit:"メッセージを封印する — $1",form_note:"メッセージは暗号化され永久に保存されます。",live_title:"ライブ — 今封印されているメッセージ",why_title:"なぜ後悔するのか？",why1_t:"あなたは存在した。",why1_d:"2036年、誰かがあなたの言葉を読み、2026年にあなたがここにいたことを知るでしょう。",why2_t:"コーヒー1杯より安い。",why2_d:"たったの$1。もっとくだらないものにお金を使ったことがあるはずです。",why3_t:"カウンターは絶対にリセットされない。",why3_d:"支払った人全員が永久記録の一部になります。",cd_title:"カプセル開封まで",days:"日",hours:"時間",mins:"分",secs:"秒",trust1:"256ビット暗号化",trust2:"Stripe決済",trust3:"永久ホスティング",transparency:"完全な透明性",modal_title:"メッセージはもうすぐ封印されます 🔒",modal_body:"$1のお支払いを完了して、メッセージを2036年まで永久に封印しましょう。",modal_pay:"Stripeで$1支払う →",modal_cancel:"後で",success_title:"あなたは今、歴史の一部です ✨",success_sub:"メッセージが封印されました。2036年1月1日にまたお越しください。",success_share:"シェアして他の人にも知らせよう：",share_tw:"Xでシェア",share_wa:"WhatsAppでシェア",share_fb:"Facebookでシェア",share_copy:"リンクをコピー",copied:"コピーしました！",footer:"© 2026 OneMessage.world · 人類の永久的な記録"},
  zh: {dir:"ltr",cta_lang:"中文",badge:"🌍 数字时间胶囊 · 2036年1月1日开封",hero1:"一条留言。",hero2:"一美元。",hero3:"永远。",sub:"为世界写下你的留言。它将被封存至2036年1月1日——然后向所有人、在每个地方、永远公开。",counter_msgs:"条留言已封存",counter_countries:"个国家",counter_raised:"已筹集",cta:"留下我的留言 — $1",cta_sub:"安全支付 · 60秒 · 成为历史的一部分",story_badge:"为什么会有这个",story_title:"人类的快照，封存于时间之中。",story_p1:"2026年，我们提出了一个简单的问题：如果你能对全世界说一件事——并且知道它会在10年后被阅读——你会说什么？",story_p2:"OneMessage.world不是产品，是永久档案。每位支付$1的人都成为2026年人类思想、希望、恐惧与爱的活体档案的一部分。",story_p3:"当时间胶囊在2036年1月1日开封时，每条留言都将永久免费公开。",story_quote:"「未来的人们看这个胶囊，就像我们看1926年埋下的时间胶囊一样。」",form_title:"为2036写下你的留言",form_name:"你的名字（可选）",form_country:"你的国家",form_msg:"写给未来的留言...",form_vis:"我的留言",form_public:"公开 — 2036年可见",form_private:"私密 — 封存至2036年",form_chars:"剩余字符",form_submit:"封存我的留言 — $1",form_note:"你的留言已加密并永久保存。",live_title:"直播 — 正在封存的留言",why_title:"为什么你会后悔不这样做？",why1_t:"你曾经存在。",why1_d:"2036年，有人会读到你的话，知道你曾在2026年活着、思考、感受。",why2_t:"比一杯咖啡还便宜。",why2_d:"只需一美元。你曾为更无聊的事花更多钱。",why3_t:"计数器永远不会重置。",why3_d:"每位付款的人都成为永久记录的一部分。",cd_title:"时间胶囊将在以下时间开封",days:"天",hours:"小时",mins:"分钟",secs:"秒",trust1:"256位加密",trust2:"Stripe支付",trust3:"永久托管",transparency:"完全透明",modal_title:"你的留言即将被封存 🔒",modal_body:"完成$1支付，将你的留言永久封存至2036年。",modal_pay:"通过Stripe支付$1 →",modal_cancel:"也许以后",success_title:"你现在是历史的一部分了 ✨",success_sub:"你的留言已封存。请在2036年1月1日回来。",success_share:"分享并激励他人留下他们的印记：",share_tw:"分享到X",share_wa:"分享到WhatsApp",share_fb:"分享到Facebook",share_copy:"复制链接",copied:"已复制！",footer:"© 2026 OneMessage.world · 人类的永久记录"},
  ko: {dir:"ltr",cta_lang:"한국어",badge:"🌍 디지털 타임캡슐 · 2036년 1월 1일 개봉",hero1:"하나의 메시지.",hero2:"1달러.",hero3:"영원히.",sub:"세상을 위한 메시지를 작성하세요. 2036년 1월 1일까지 봉인되었다가, 그날 모든 사람에게 영원히 공개됩니다.",counter_msgs:"개 봉인됨",counter_countries:"개국",counter_raised:"모금됨",cta:"내 메시지 남기기 — $1",cta_sub:"안전한 결제 · 60초 · 역사의 일부가 되세요",story_badge:"왜 이것이 존재하는가",story_title:"시간 속에 봉인된 인류의 스냅샷.",story_p1:"2026년, 우리는 간단한 질문을 던졌습니다: 세상 전체에 한 가지를 말할 수 있다면, 그리고 10년 후에 읽힌다는 걸 안다면, 무엇을 말하겠습니까?",story_p2:"OneMessage.world는 제품이 아닙니다. 영구적인 기록입니다. $1을 지불하는 모든 사람이 2026년 인류의 생각, 희망, 두려움, 사랑의 살아있는 아카이브의 일부가 됩니다.",story_p3:"캡슐이 2036년 1월 1일에 열리면, 모든 메시지는 영원히 무료로 공개됩니다.",story_quote:"\"미래 세대는 이 캡슐을 우리가 1926년에 묻힌 타임캡슐을 보는 것처럼 볼 것입니다.\"",form_title:"2036년을 위한 메시지 작성",form_name:"이름 (선택사항)",form_country:"국가",form_msg:"미래를 위한 메시지...",form_vis:"내 메시지는",form_public:"공개 — 2036년에 표시",form_private:"비공개 — 2036년까지 봉인",form_chars:"자 남음",form_submit:"내 메시지 봉인 — $1",form_note:"메시지는 암호화되어 영구적으로 저장됩니다.",live_title:"라이브 — 지금 봉인되는 메시지",why_title:"왜 후회하게 될까요?",why1_t:"당신은 존재했습니다.",why1_d:"2036년, 누군가 당신의 말을 읽고 당신이 2026년에 여기 있었다는 걸 알게 됩니다.",why2_t:"커피 한 잔보다 저렴합니다.",why2_d:"단 $1. 이미 잊어버린 것들에 더 많이 썼을 겁니다.",why3_t:"카운터는 절대 초기화되지 않습니다.",why3_d:"결제하는 모든 사람이 영구 기록의 일부가 됩니다.",cd_title:"캡슐 개봉까지",days:"일",hours:"시간",mins:"분",secs:"초",trust1:"256비트 암호화",trust2:"Stripe 결제",trust3:"영구 호스팅",transparency:"완전한 투명성",modal_title:"메시지가 곧 봉인됩니다 🔒",modal_body:"$1 결제를 완료하여 2036년까지 메시지를 영구 봉인하세요.",modal_pay:"Stripe로 $1 결제 →",modal_cancel:"나중에",success_title:"이제 당신은 역사의 일부입니다 ✨",success_sub:"메시지가 봉인되었습니다. 2036년 1월 1일에 돌아오세요.",success_share:"공유하고 다른 사람들에게 영감을 주세요:",share_tw:"X에서 공유",share_wa:"WhatsApp에서 공유",share_fb:"Facebook에서 공유",share_copy:"링크 복사",copied:"복사됨!",footer:"© 2026 OneMessage.world · 인류의 영구적인 기록"},
  hi: {dir:"ltr",cta_lang:"हिन्दी",badge:"🌍 डिजिटल टाइम कैप्सूल · 1 जनवरी 2036 को खुलेगा",hero1:"एक संदेश।",hero2:"एक डॉलर।",hero3:"हमेशा के लिए।",sub:"दुनिया के लिए अपना संदेश लिखें। यह 1 जनवरी 2036 तक सील रहेगा — फिर सभी के लिए, हर जगह, हमेशा के लिए प्रकट होगा।",counter_msgs:"संदेश सील",counter_countries:"देश",counter_raised:"एकत्रित",cta:"मेरा संदेश छोड़ें — $1",cta_sub:"सुरक्षित भुगतान · 60 सेकंड · इतिहास का हिस्सा बनें",story_badge:"यह क्यों मौजूद है",story_title:"समय में सील मानवता की एक तस्वीर।",story_p1:"2026 में, हमने एक सरल सवाल पूछा: अगर आप पूरी दुनिया को एक बात कह सकते — और जानते कि 10 साल बाद पढ़ी जाएगी — तो क्या कहते?",story_p2:"OneMessage.world कोई उत्पाद नहीं है। यह एक स्थायी रिकॉर्ड है। $1 देने वाला हर व्यक्ति 2026 की मानवता के जीवित संग्रह का हिस्सा बन जाता है।",story_p3:"जब 1 जनवरी 2036 को कैप्सूल खुलेगा, तो हर संदेश हमेशा के लिए मुफ्त में प्रकाशित किया जाएगा।",story_quote:"\"भावी पीढ़ियां इस कैप्सूल को वैसे ही देखेंगी जैसे हम 1926 में दबे कैप्सूल को देखते हैं।\"",form_title:"2036 के लिए अपना संदेश लिखें",form_name:"आपका नाम (वैकल्पिक)",form_country:"आपका देश",form_msg:"भविष्य के लिए आपका संदेश...",form_vis:"मेरा संदेश",form_public:"सार्वजनिक — 2036 में दिखेगा",form_private:"निजी — 2036 तक सील",form_chars:"अक्षर शेष",form_submit:"मेरा संदेश सील करें — $1",form_note:"आपका संदेश एन्क्रिप्टेड और स्थायी रूप से संग्रहीत है।",live_title:"लाइव — अभी सील हो रहे संदेश",why_title:"आप पछताएंगे क्यों?",why1_t:"आप अस्तित्व में थे।",why1_d:"2036 में, कोई आपके शब्द पढ़ेगा और जानेगा कि आप 2026 में यहाँ थे।",why2_t:"एक कॉफी से सस्ता।",why2_d:"एक डॉलर। आपने उन चीजों पर ज्यादा खर्च किया जो आप भूल गए।",why3_t:"काउंटर कभी रीसेट नहीं होगा।",why3_d:"भुगतान करने वाला हर व्यक्ति स्थायी रिकॉर्ड का हिस्सा बनता है।",cd_title:"कैप्सूल खुलने में",days:"दिन",hours:"घंटे",mins:"मिनट",secs:"सेकंड",trust1:"256-बिट एन्क्रिप्शन",trust2:"Stripe भुगतान",trust3:"स्थायी होस्टिंग",transparency:"पूर्ण पारदर्शिता",modal_title:"आपका संदेश लगभग सील हो गया 🔒",modal_body:"$1 का भुगतान पूरा करें और 2036 तक अपने संदेश को स्थायी रूप से सील करें।",modal_pay:"Stripe से $1 दें →",modal_cancel:"शायद बाद में",success_title:"अब आप इतिहास का हिस्सा हैं ✨",success_sub:"आपका संदेश सील हो गया। 1 जनवरी 2036 को वापस आएं।",success_share:"शेयर करें और दूसरों को प्रेरित करें:",share_tw:"X पर शेयर",share_wa:"WhatsApp पर शेयर",share_fb:"Facebook पर शेयर",share_copy:"लिंक कॉपी",copied:"कॉपी हो गया!",footer:"© 2026 OneMessage.world · मानवता का स्थायी रिकॉर्ड"},
  tr: {dir:"ltr",cta_lang:"TR",badge:"🌍 Dijital Zaman Kapsülü · 1 Ocak 2036'da Açılıyor",hero1:"Bir mesaj.",hero2:"Bir dolar.",hero3:"Sonsuza kadar.",sub:"Dünya için mesajınızı yazın. 1 Ocak 2036'ya kadar mühürlenecek — ardından herkese, her yerde, sonsuza kadar açılacak.",counter_msgs:"mesaj mühürlendi",counter_countries:"ülke",counter_raised:"toplandı",cta:"Mesajımı Bırak — $1",cta_sub:"Güvenli ödeme · 60 saniye · Tarihin parçası ol",story_badge:"NEDEN MEVCUT",story_title:"Zamana mühürlenmiş bir insanlık fotoğrafı.",story_p1:"2026'da basit bir soru sorduk: Tüm dünyaya bir şey söyleyebilseydiniz — ve 10 yıl sonra okunacağını bilseydiniz — ne söylerdiniz?",story_p2:"OneMessage.world bir ürün değil. Kalıcı bir kayıt. $1 ödeyen herkes, 2026'daki insan düşüncesi, umut, korku ve sevginin canlı arşivinin bir parçası olur.",story_p3:"Kapsül 1 Ocak 2036'da açıldığında, her mesaj sonsuza kadar ücretsiz yayınlanacak.",story_quote:"\"Gelecek nesiller bu kapsüle, biz 1926'da gömülen kapsüllere bakar gibi bakacak.\"",form_title:"2036 için mesajını yaz",form_name:"Adınız (isteğe bağlı)",form_country:"Ülkeniz",form_msg:"Geleceğe mesajınız...",form_vis:"Mesajım",form_public:"Herkese açık — 2036'da görünür",form_private:"Gizli — 2036'ya kadar mühürlü",form_chars:"karakter kaldı",form_submit:"Mesajımı Mühürle — $1",form_note:"Mesajınız şifrelenir ve kalıcı olarak saklanır.",live_title:"Canlı — Şu An Mühürlenen Mesajlar",why_title:"Neden pişman olacaksınız?",why1_t:"Var oldunuz.",why1_d:"2036'da biri sizin sözlerinizi okuyacak ve 2026'da burada olduğunuzu bilecek.",why2_t:"Bir kahveden ucuz.",why2_d:"Bir dolar. Zaten unuttuğunuz şeylere daha fazla harcadınız.",why3_t:"Sayaç hiç sıfırlanmaz.",why3_d:"Ödeme yapan herkes kalıcı bir kaydın parçası olur.",cd_title:"Kapsül şu kadar sonra açılıyor",days:"Gün",hours:"Saat",mins:"Dakika",secs:"Saniye",trust1:"256-bit şifreleme",trust2:"Stripe ödemesi",trust3:"Kalıcı barındırma",transparency:"Tam Şeffaflık",modal_title:"Mesajınız neredeyse mühürlendi 🔒",modal_body:"$1 ödemenizi tamamlayın ve mesajınızı 2036'ya kadar kalıcı olarak mühürleyin.",modal_pay:"Stripe ile $1 öde →",modal_cancel:"Belki sonra",success_title:"Artık tarihin bir parçasısınız ✨",success_sub:"Mesajınız mühürlendi. 1 Ocak 2036'da geri gelin.",success_share:"Paylaşın ve başkalarına ilham verin:",share_tw:"X'te Paylaş",share_wa:"WhatsApp'ta Paylaş",share_fb:"Facebook'ta Paylaş",share_copy:"Bağlantıyı Kopyala",copied:"Kopyalandı!",footer:"© 2026 OneMessage.world · İnsanlığın kalıcı kaydı"},
  ru: {dir:"ltr",cta_lang:"RU",badge:"🌍 Цифровая Капсула Времени · Открывается 1 января 2036",hero1:"Одно сообщение.",hero2:"Один доллар.",hero3:"Навсегда.",sub:"Напишите своё послание миру. Оно будет запечатано до 1 января 2036 года — затем открыто для всех, везде, навсегда.",counter_msgs:"сообщений запечатано",counter_countries:"стран",counter_raised:"собрано",cta:"Оставить Моё Послание — $1",cta_sub:"Безопасный платёж · 60 секунд · Стань частью истории",story_badge:"ЗАЧЕМ ЭТО СУЩЕСТВУЕТ",story_title:"Снимок человечества, запечатанный во времени.",story_p1:"В 2026 году мы задали простой вопрос: если бы вы могли сказать одну вещь всему миру — и знали, что её прочтут через 10 лет — что бы вы сказали?",story_p2:"OneMessage.world — не продукт. Это постоянный архив. Каждый, кто платит $1, становится частью живого свидетельства человеческой мысли, надежды и любви — такими, какими они были в 2026 году.",story_p3:"Когда капсула откроется 1 января 2036 года, каждое послание будет опубликовано бесплатно навсегда.",story_quote:"«Будущие поколения будут смотреть на эту капсулу так же, как мы смотрим на те, что были зарыты в 1926 году.»",form_title:"Напишите ваше послание для 2036",form_name:"Ваше имя (необязательно)",form_country:"Ваша страна",form_msg:"Ваше послание будущему...",form_vis:"Моё послание",form_public:"Публичное — видно в 2036",form_private:"Приватное — запечатано до 2036",form_chars:"символов осталось",form_submit:"Запечатать Моё Послание — $1",form_note:"Ваше послание зашифровано и хранится постоянно.",live_title:"В Прямом Эфире — Запечатываемые сейчас послания",why_title:"Почему вы пожалеете?",why1_t:"Вы существовали.",why1_d:"В 2036 году кто-то прочтёт ваши слова и узнает, что вы были здесь, живыми в 2026 году.",why2_t:"Дешевле чашки кофе.",why2_d:"Один доллар. Вы тратили больше на то, что уже забыли.",why3_t:"Счётчик никогда не обнуляется.",why3_d:"Каждый, кто платит, становится частью постоянного архива.",cd_title:"Капсула открывается через",days:"Дней",hours:"Часов",mins:"Минут",secs:"Секунд",trust1:"256-битное шифрование",trust2:"Платёж Stripe",trust3:"Вечный хостинг",transparency:"Полная Прозрачность",modal_title:"Ваше послание почти запечатано 🔒",modal_body:"Завершите оплату $1, чтобы навсегда запечатать ваше послание до 2036 года.",modal_pay:"Заплатить $1 через Stripe →",modal_cancel:"Может быть позже",success_title:"Вы теперь часть истории ✨",success_sub:"Ваше послание запечатано. Вернитесь 1 января 2036 года.",success_share:"Поделитесь и вдохновите других:",share_tw:"Поделиться в X",share_wa:"Поделиться в WhatsApp",share_fb:"Поделиться в Facebook",share_copy:"Копировать ссылку",copied:"Скопировано!",footer:"© 2026 OneMessage.world · Постоянная летопись человечества"},
  id: {dir:"ltr",cta_lang:"ID",badge:"🌍 Kapsul Waktu Digital · Dibuka 1 Januari 2036",hero1:"Satu pesan.",hero2:"Satu dolar.",hero3:"Selamanya.",sub:"Tulis pesanmu untuk dunia. Akan disegel hingga 1 Januari 2036 — lalu diungkapkan kepada semua orang, di mana saja, selamanya.",counter_msgs:"pesan tersegel",counter_countries:"negara",counter_raised:"terkumpul",cta:"Tinggalkan Pesanku — $1",cta_sub:"Pembayaran aman · 60 detik · Jadilah bagian dari sejarah",story_badge:"MENGAPA INI ADA",story_title:"Foto manusia, tersegel dalam waktu.",story_p1:"Pada 2026, kami mengajukan pertanyaan sederhana: jika kamu bisa mengatakan satu hal kepada seluruh dunia — dan tahu akan dibaca 10 tahun kemudian — apa yang akan kamu katakan?",story_p2:"OneMessage.world bukan produk. Ini adalah catatan permanen. Setiap orang yang membayar $1 menjadi bagian dari arsip hidup pemikiran, harapan, dan cinta manusia — persis seperti di 2026.",story_p3:"Ketika kapsul dibuka pada 1 Januari 2036, setiap pesan akan diterbitkan secara gratis selamanya.",story_quote:"\"Generasi mendatang akan melihat kapsul ini seperti kita melihat yang dikubur pada 1926.\"",form_title:"Tulis pesanmu untuk 2036",form_name:"Namamu (opsional)",form_country:"Negaramu",form_msg:"Pesanmu untuk masa depan...",form_vis:"Pesanku",form_public:"Publik — terlihat di 2036",form_private:"Privat — tersegel hingga 2036",form_chars:"karakter tersisa",form_submit:"Segel Pesanku — $1",form_note:"Pesanmu dienkripsi dan disimpan secara permanen.",live_title:"Langsung — Pesan yang Sedang Disegel Sekarang",why_title:"Mengapa kamu akan menyesal?",why1_t:"Kamu pernah ada.",why1_d:"Di 2036, seseorang akan membaca kata-katamu dan tahu kamu ada di sini, hidup di 2026.",why2_t:"Lebih murah dari secangkir kopi.",why2_d:"Satu dolar. Kamu sudah menghabiskan lebih banyak untuk hal-hal yang sudah dilupakan.",why3_t:"Penghitung tidak pernah direset.",why3_d:"Setiap orang yang membayar masuk ke dalam catatan permanen.",cd_title:"Kapsul dibuka dalam",days:"Hari",hours:"Jam",mins:"Menit",secs:"Detik",trust1:"Enkripsi 256-bit",trust2:"Pembayaran Stripe",trust3:"Hosting permanen",transparency:"Transparansi Penuh",modal_title:"Pesanmu hampir tersegel 🔒",modal_body:"Selesaikan pembayaran $1 untuk menyegel pesanmu secara permanen hingga 2036.",modal_pay:"Bayar $1 dengan Stripe →",modal_cancel:"Mungkin nanti",success_title:"Kamu sekarang bagian dari sejarah ✨",success_sub:"Pesanmu tersegel. Kembalilah pada 1 Januari 2036.",success_share:"Bagikan dan inspirasi orang lain:",share_tw:"Bagikan di X",share_wa:"Bagikan di WhatsApp",share_fb:"Bagikan di Facebook",share_copy:"Salin Tautan",copied:"Disalin!",footer:"© 2026 OneMessage.world · Catatan permanen kemanusiaan"},
};

const IP_MAP={BR:"pt",SA:"ar",AE:"ar",EG:"ar",IQ:"ar",JO:"ar",KW:"ar",LB:"ar",LY:"ar",MA:"ar",OM:"ar",QA:"ar",SD:"ar",SY:"ar",TN:"ar",YE:"ar",DZ:"ar",ES:"es",MX:"es",AR:"es",CO:"es",CL:"es",PE:"es",VE:"es",EC:"es",BO:"es",GT:"es",FR:"fr",CI:"fr",SN:"fr",DE:"de",AT:"de",IT:"it",JP:"ja",CN:"zh",TW:"zh",HK:"zh",KR:"ko",IN:"hi",TR:"tr",RU:"ru",BY:"ru",KZ:"ru",ID:"id"};

const COUNTRIES=["🇺🇸 United States","🇧🇷 Brazil","🇸🇦 Saudi Arabia","🇦🇪 UAE","🇪🇬 Egypt","🇮🇶 Iraq","🇯🇴 Jordan","🇱🇧 Lebanon","🇲🇦 Morocco","🇩🇿 Algeria","🇹🇳 Tunisia","🇶🇦 Qatar","🇰🇼 Kuwait","🇮🇳 India","🇬🇧 UK","🇫🇷 France","🇩🇪 Germany","🇪🇸 Spain","🇲🇽 Mexico","🇨🇦 Canada","🇦🇺 Australia","🇯🇵 Japan","🇨🇳 China","🇰🇷 South Korea","🇮🇹 Italy","🇵🇹 Portugal","🇷🇺 Russia","🇹🇷 Turkey","🇮🇩 Indonesia","🇵🇰 Pakistan","🇦🇫 Afghanistan","🇦🇱 Albania","🇦🇩 Andorra","🇦🇴 Angola","🇦🇬 Antigua and Barbuda","🇦🇷 Argentina","🇦🇲 Armenia","🇦🇹 Austria","🇦🇿 Azerbaijan","🇧🇸 Bahamas","🇧🇭 Bahrain","🇧🇩 Bangladesh","🇧🇧 Barbados","🇧🇾 Belarus","🇧🇪 Belgium","🇧🇿 Belize","🇧🇯 Benin","🇧🇹 Bhutan","🇧🇴 Bolivia","🇧🇦 Bosnia and Herzegovina","🇧🇼 Botswana","🇧🇳 Brunei","🇧🇬 Bulgaria","🇧🇫 Burkina Faso","🇧🇮 Burundi","🇨🇻 Cabo Verde","🇰🇭 Cambodia","🇨🇲 Cameroon","🇨🇫 Central African Republic","🇹🇩 Chad","🇨🇱 Chile","🇨🇴 Colombia","🇰🇲 Comoros","🇨🇩 Congo (DR)","🇨🇬 Congo (Republic)","🇨🇷 Costa Rica","🇨🇮 Côte d'Ivoire","🇭🇷 Croatia","🇨🇺 Cuba","🇨🇾 Cyprus","🇨🇿 Czech Republic","🇩🇰 Denmark","🇩🇯 Djibouti","🇩🇲 Dominica","🇩🇴 Dominican Republic","🇪🇨 Ecuador","🇸🇻 El Salvador","🇬🇶 Equatorial Guinea","🇪🇷 Eritrea","🇪🇪 Estonia","🇸🇿 Eswatini","🇪🇹 Ethiopia","🇫🇯 Fiji","🇫🇮 Finland","🇬🇦 Gabon","🇬🇲 Gambia","🇬🇪 Georgia","🇬🇭 Ghana","🇬🇷 Greece","🇬🇩 Grenada","🇬🇹 Guatemala","🇬🇳 Guinea","🇬🇼 Guinea-Bissau","🇬🇾 Guyana","🇭🇹 Haiti","🇭🇳 Honduras","🇭🇺 Hungary","🇮🇸 Iceland","🇮🇷 Iran","🇮🇪 Ireland","🇮🇱 Israel","🇯🇲 Jamaica","🇰🇿 Kazakhstan","🇰🇪 Kenya","🇰🇮 Kiribati","🇽🇰 Kosovo","🇰🇬 Kyrgyzstan","🇱🇦 Laos","🇱🇻 Latvia","🇱🇸 Lesotho","🇱🇷 Liberia","🇱🇾 Libya","🇱🇮 Liechtenstein","🇱🇹 Lithuania","🇱🇺 Luxembourg","🇲🇬 Madagascar","🇲🇼 Malawi","🇲🇾 Malaysia","🇲🇻 Maldives","🇲🇱 Mali","🇲🇹 Malta","🇲🇭 Marshall Islands","🇲🇷 Mauritania","🇲🇺 Mauritius","🇫🇲 Micronesia","🇲🇩 Moldova","🇲🇨 Monaco","🇲🇳 Mongolia","🇲🇪 Montenegro","🇲🇿 Mozambique","🇲🇲 Myanmar","🇳🇦 Namibia","🇳🇷 Nauru","🇳🇵 Nepal","🇳🇱 Netherlands","🇳🇿 New Zealand","🇳🇮 Nicaragua","🇳🇪 Niger","🇳🇬 Nigeria","🇰🇵 North Korea","🇲🇰 North Macedonia","🇳🇴 Norway","🇴🇲 Oman","🇵🇼 Palau","🇵🇸 Palestine","🇵🇦 Panama","🇵🇬 Papua New Guinea","🇵🇾 Paraguay","🇵🇪 Peru","🇵🇭 Philippines","🇵🇱 Poland","🇷🇴 Romania","🇷🇼 Rwanda","🇰🇳 Saint Kitts and Nevis","🇱🇨 Saint Lucia","🇻🇨 Saint Vincent and the Grenadines","🇼🇸 Samoa","🇸🇲 San Marino","🇸🇹 São Tomé and Príncipe","🇸🇳 Senegal","🇷🇸 Serbia","🇸🇨 Seychelles","🇸🇱 Sierra Leone","🇸🇬 Singapore","🇸🇰 Slovakia","🇸🇮 Slovenia","🇸🇧 Solomon Islands","🇸🇴 Somalia","🇿🇦 South Africa","🇸🇸 South Sudan","🇱🇰 Sri Lanka","🇸🇩 Sudan","🇸🇷 Suriname","🇸🇪 Sweden","🇨🇭 Switzerland","🇸🇾 Syria","🇹🇼 Taiwan","🇹🇯 Tajikistan","🇹🇿 Tanzania","🇹🇭 Thailand","🇹🇱 Timor-Leste","🇹🇬 Togo","🇹🇴 Tonga","🇹🇹 Trinidad and Tobago","🇹🇻 Tuvalu","🇺🇬 Uganda","🇺🇦 Ukraine","🇺🇾 Uruguay","🇺🇿 Uzbekistan","🇻🇺 Vanuatu","🇻🇦 Vatican City","🇻🇪 Venezuela","🇻🇳 Vietnam","🇾🇪 Yemen","🇿🇲 Zambia","🇿🇼 Zimbabwe","🌍 Other"];

const FEED=[{f:"🇺🇸",n:"J. Williams",t:"2m"},{f:"🇧🇷",n:"M. Silva",t:"5m"},{f:"🇸🇦",n:"Khaled A.",t:"8m"},{f:"🇯🇵",n:"Y. Tanaka",t:"11m"},{f:"🇩🇪",n:"F. Müller",t:"15m"},{f:"🇮🇳",n:"P. Sharma",t:"18m"},{f:"🇫🇷",n:"C. Dupont",t:"22m"},{f:"🇰🇷",n:"J. Kim",t:"25m"},{f:"🇲🇽",n:"L. García",t:"29m"},{f:"🇦🇪",n:"Fatima K.",t:"33m"},{f:"🇨🇳",n:"Wei Zhang",t:"37m"},{f:"🇬🇧",n:"S. Patel",t:"41m"}];

function Stars(){
  const r=useRef();
  useEffect(()=>{
    const c=r.current,ctx=c.getContext("2d");
    let W=c.width=window.innerWidth,H=c.height=window.innerHeight;
    const s=Array.from({length:180},()=>({x:Math.random()*W,y:Math.random()*H,r:Math.random()*1.3+.2,a:Math.random(),d:Math.random()*.004+.001}));
    let raf;const draw=()=>{ctx.clearRect(0,0,W,H);s.forEach(p=>{p.a+=p.d;if(p.a>1||p.a<0)p.d=-p.d;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle=`rgba(212,175,55,${Math.abs(p.a)})`;ctx.fill();});raf=requestAnimationFrame(draw);};draw();
    const rz=()=>{W=c.width=window.innerWidth;H=c.height=window.innerHeight;};window.addEventListener("resize",rz);
    return()=>{cancelAnimationFrame(raf);window.removeEventListener("resize",rz);};
  },[]);
  return <canvas ref={r} style={{position:"fixed",top:0,left:0,pointerEvents:"none",zIndex:0}}/>;
}

function useCD(){
  const tgt=new Date("2036-01-01T00:00:00Z").getTime();
  const calc=()=>{const d=tgt-Date.now();if(d<=0)return{d:0,h:0,m:0,s:0};return{d:Math.floor(d/86400000),h:Math.floor((d%86400000)/3600000),m:Math.floor((d%3600000)/60000),s:Math.floor((d%60000)/1000)};};
  const[t,setT]=useState(calc);
  useEffect(()=>{const id=setInterval(()=>setT(calc()),1000);return()=>clearInterval(id);},[]);
  return t;
}

function useAnim(tgt){
  const[v,setV]=useState(0);
  useEffect(()=>{let i=0,steps=60;const id=setInterval(()=>{i++;setV(Math.floor(tgt*(i/steps)));if(i>=steps){setV(tgt);clearInterval(id);}},20);return()=>clearInterval(id);},[tgt]);
  return v;
}

export default function App(){
  const[lang,setLang]=useState("en");
  const[count,setCount]=useState(0);
  const[raised,setRaised]=useState(0);
  const[form,setForm]=useState({name:"",country:"",msg:"",vis:"public"});
  const[modal,setModal]=useState(false);
  const[agreed,setAgreed]=useState(false);
  const[success,setSuccess]=useState(false);
  const[loading,setLoading]=useState(false);
  const[copied,setCopied]=useState(false);
  const[showForm,setShowForm]=useState(false);
  const[feed,setFeed]=useState(FEED);
  const formRef=useRef();
  const cd=useCD();
  const ac=useAnim(count);
  const t=T[lang]||T.en;
  const rtl=t.dir==="rtl";
  const MAX=280;

  useEffect(()=>{
    fetch("https://ipapi.co/json/").then(r=>r.json()).then(d=>{const l=IP_MAP[d.country_code];if(l)setLang(l);}).catch(()=>{});
    const loadStats=()=>fetch("/api/stats").then(r=>r.json()).then(d=>{if(typeof d.count==="number")setCount(d.count);if(typeof d.raised==="number")setRaised(d.raised);}).catch(()=>{});
    loadStats();
    const si=setInterval(loadStats,30000);
    return()=>clearInterval(si);
  },[]);

  useEffect(()=>{
    const flagOf=(c)=>{if(!c)return"🌍";const p=c.split(" ");return p[0]||"🌍";};
    const timeAgo=(ts)=>{const s=Math.floor((Date.now()-new Date(ts))/1000);if(s<60)return`${s}s`;if(s<3600)return`${Math.floor(s/60)}m`;if(s<86400)return`${Math.floor(s/3600)}h`;return`${Math.floor(s/86400)}d`;};
    const loadFeed=()=>fetch("/api/recent-messages").then(r=>r.json()).then(d=>{
      const real=(d.messages||[]).map(m=>({f:flagOf(m.country),n:m.name||"Anonymous",t:timeAgo(m.created_at),real:true}));
      const needed=12-real.length;
      const filled=needed>0?[...real,...FEED.slice(0,needed)]:real;
      setFeed(filled);
    }).catch(()=>{});
    loadFeed();
    const fi=setInterval(loadFeed,60000);
    return()=>clearInterval(fi);
  },[]);

  const goForm=()=>{setShowForm(true);setTimeout(()=>formRef.current?.scrollIntoView({behavior:"smooth",block:"start"}),80);};
  const pay=()=>{setModal(false);setAgreed(false);setSuccess(true);const nc=count+1,nr=parseFloat((raised+0.67).toFixed(2));setCount(nc);setRaised(nr);};
  const st=()=>{const m={en:"I just sealed my message for the world 🌍 Opens 2036 → OneMessage.world #OneMessage2036",ar:"تركتُ رسالتي للعالم 🌍 تُفتح 2036 ← OneMessage.world",pt:"Deixei minha mensagem para o mundo 🌍 Abre em 2036 → OneMessage.world",es:"Dejé mi mensaje para el mundo 🌍 Se abre en 2036 → OneMessage.world",fr:"J'ai laissé mon message pour le monde 🌍 S'ouvre en 2036 → OneMessage.world",de:"Ich habe meine Nachricht für die Welt hinterlassen 🌍 Öffnet 2036 → OneMessage.world",it:"Ho lasciato il mio messaggio per il mondo 🌍 Si apre nel 2036 → OneMessage.world",ja:"世界へのメッセージを残しました 🌍 2036年開封 → OneMessage.world",zh:"我留下了给世界的留言 🌍 2036年开封 → OneMessage.world",ko:"세상을 위한 메시지를 남겼습니다 🌍 2036년 개봉 → OneMessage.world",hi:"मैंने दुनिया के लिए अपना संदेश छोड़ा 🌍 2036 में खुलेगा → OneMessage.world",tr:"Dünya için mesajımı bıraktım 🌍 2036'da açılıyor → OneMessage.world",ru:"Я оставил послание миру 🌍 Открывается в 2036 → OneMessage.world",id:"Saya meninggalkan pesan untuk dunia 🌍 Dibuka 2036 → OneMessage.world"};return encodeURIComponent(m[lang]||m.en);};
  const cpLink=()=>{navigator.clipboard?.writeText("https://onemessage.world").then(()=>{setCopied(true);setTimeout(()=>setCopied(false),2000);}).catch(()=>{});};

  return(<>
  <Head>
    <title>OneMessage.world — Leave your message for 2036</title>
    <meta name="description" content="Pay $1, seal your message for humanity. Opens January 1, 2036."/>
    <meta property="og:title" content="OneMessage.world — Leave your message for 2036"/>
    <meta property="og:description" content="Pay $1, seal your message for humanity. Opens January 1, 2036."/>
    <meta property="og:image" content="https://onemessage.world/og.png"/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://onemessage.world"/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:title" content="OneMessage.world — Leave your message for 2036"/>
    <meta name="twitter:description" content="Pay $1, seal your message for humanity. Opens January 1, 2036."/>
    <meta name="twitter:image" content="https://onemessage.world/og.png"/>
    <link rel="canonical" href="https://onemessage.world"/>
  </Head>
  <style>{`
    @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;0,700;1,400&family=DM+Sans:wght@300;400;500;600&display=swap');
    *{margin:0;padding:0;box-sizing:border-box}
    :root{--g:#D4AF37;--bg:#05070F;--bg2:#090C18;--sf:rgba(255,255,255,.034);--br:rgba(212,175,55,.17);--tx:#EDE8D8;--mt:rgba(237,232,216,.52)}
    body{background:var(--bg);color:var(--tx);font-family:'DM Sans',sans-serif;min-height:100vh;overflow-x:hidden}
    nav{position:fixed;top:0;left:0;right:0;z-index:100;padding:14px 28px;display:flex;justify-content:space-between;align-items:center;background:linear-gradient(to bottom,rgba(5,7,15,.95),transparent);backdrop-filter:blur(14px)}
    .nlo{font-family:'Cormorant Garamond',serif;font-size:1.1rem;color:var(--g);letter-spacing:.06em;white-space:nowrap}
    .lbs{display:flex;gap:4px;flex-wrap:wrap;max-width:72%;justify-content:flex-end}
    .lb{background:none;border:1px solid var(--br);color:var(--mt);padding:3px 7px;border-radius:20px;cursor:pointer;font-size:.63rem;font-family:'DM Sans',sans-serif;transition:all .2s;white-space:nowrap}
    .lb:hover,.lb.on{background:var(--g);color:#000;border-color:var(--g)}
    .hero{min-height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:120px 20px 100px;position:relative;z-index:1}
    .bdg{display:inline-block;background:rgba(212,175,55,.07);border:1px solid var(--br);color:var(--g);padding:6px 20px;border-radius:30px;font-size:.7rem;letter-spacing:.13em;text-transform:uppercase;margin-bottom:44px;animation:fu .9s ease both}
    .ht{font-family:'Cormorant Garamond',serif;font-size:clamp(3rem,10vw,9rem);font-weight:700;line-height:.93}
    .ht span{display:block;animation:fu .9s ease both}
    .ht span:nth-child(1){color:var(--tx);animation-delay:.1s}
    .ht span:nth-child(2){color:var(--g);animation-delay:.2s}
    .ht span:nth-child(3){color:var(--tx);font-style:italic;animation-delay:.3s}
    .hs{max-width:550px;color:var(--mt);font-size:1rem;line-height:1.78;margin:28px auto 52px;animation:fu .9s .4s ease both;opacity:0;animation-fill-mode:forwards}
    .dv{width:50px;height:1px;background:linear-gradient(90deg,transparent,var(--g),transparent);margin:0 auto}
    .cr{display:flex;gap:clamp(20px,5vw,68px);justify-content:center;margin-bottom:56px;animation:fu .9s .5s ease both;opacity:0;animation-fill-mode:forwards;flex-wrap:wrap}
    .ci{text-align:center}.cn{font-family:'Cormorant Garamond',serif;font-size:2.3rem;font-weight:700;color:var(--g)}.cl{font-size:.7rem;color:var(--mt);letter-spacing:.06em;margin-top:3px}
    .cb{display:inline-block;background:linear-gradient(135deg,var(--g),#9A7A0A);color:#000;padding:17px 50px;border-radius:3px;font-size:1rem;font-weight:600;cursor:pointer;border:none;font-family:'DM Sans',sans-serif;letter-spacing:.02em;transition:all .3s;box-shadow:0 0 48px rgba(212,175,55,.26);animation:fu .9s .6s ease both;opacity:0;animation-fill-mode:forwards}
    .cb:hover{transform:translateY(-3px);box-shadow:0 10px 64px rgba(212,175,55,.48)}
    .cs{font-size:.73rem;color:var(--mt);margin-top:11px;letter-spacing:.04em}
    .story{padding:96px 20px;max-width:740px;margin:0 auto;position:relative;z-index:1;text-align:center}
    .sbdg{display:inline-block;color:var(--g);font-size:.68rem;letter-spacing:.2em;text-transform:uppercase;border-top:1px solid var(--br);border-bottom:1px solid var(--br);padding:5px 18px;margin-bottom:32px}
    .story h2{font-family:'Cormorant Garamond',serif;font-size:clamp(1.7rem,4vw,2.8rem);font-weight:600;margin-bottom:28px;line-height:1.25}
    .story p{color:var(--mt);font-size:.97rem;line-height:1.82;margin-bottom:16px}
    .story blockquote{margin:36px auto;max-width:540px;font-family:'Cormorant Garamond',serif;font-style:italic;font-size:1.2rem;color:var(--g);line-height:1.65;padding:18px 28px;border-left:2px solid var(--br)}
    .rtl .story blockquote{border-left:none;border-right:2px solid var(--br)}
    .live{background:var(--bg2);border-top:1px solid var(--br);border-bottom:1px solid var(--br);padding:56px 20px;position:relative;z-index:1}
    .live h3{font-family:'Cormorant Garamond',serif;font-size:1.5rem;text-align:center;margin-bottom:32px;color:var(--g)}
    .lfg{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px;max-width:880px;margin:0 auto}
    .lfc{background:var(--sf);border:1px solid var(--br);border-radius:6px;padding:12px 14px;display:flex;align-items:center;gap:10px}
    .lfi{flex:1;min-width:0}.lfn{font-size:.82rem;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.lft{font-size:.68rem;color:var(--mt);margin-top:2px}
    .lfd{width:6px;height:6px;background:#22c55e;border-radius:50%;flex-shrink:0;box-shadow:0 0 6px #22c55e}
    .trans{padding:72px 20px;max-width:780px;margin:0 auto;position:relative;z-index:1}
    .trans h3{font-family:'Cormorant Garamond',serif;font-size:1.7rem;text-align:center;margin-bottom:44px;color:var(--g)}
    .tg{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:14px}
    .tc{background:var(--sf);border:1px solid var(--br);border-radius:8px;padding:24px;text-align:center}
    .tn{font-family:'Cormorant Garamond',serif;font-size:1.85rem;font-weight:700;color:var(--g)}.tl{font-size:.73rem;color:var(--mt);margin-top:5px;letter-spacing:.05em}
    .cd{background:var(--bg2);border-top:1px solid var(--br);border-bottom:1px solid var(--br);padding:68px 20px;text-align:center;position:relative;z-index:1}
    .cd h3{font-family:'Cormorant Garamond',serif;font-size:.9rem;color:var(--mt);letter-spacing:.2em;text-transform:uppercase;margin-bottom:40px}
    .cdg{display:flex;gap:clamp(10px,4vw,52px);justify-content:center;align-items:flex-end;flex-wrap:wrap}
    .cdi{text-align:center;min-width:55px}.cdn{font-family:'Cormorant Garamond',serif;font-size:clamp(2.4rem,7vw,5.5rem);font-weight:700;color:var(--g);line-height:1;font-variant-numeric:tabular-nums}.cdl{font-size:.68rem;color:var(--mt);letter-spacing:.1em;text-transform:uppercase;margin-top:7px}
    .cds{font-family:'Cormorant Garamond',serif;font-size:2.5rem;color:var(--br);padding-bottom:14px}
    .fsec{max-width:660px;margin:0 auto;padding:72px 20px;position:relative;z-index:1}
    .fsec h2{font-family:'Cormorant Garamond',serif;font-size:2rem;text-align:center;margin-bottom:36px;color:var(--g)}
    .fc{background:var(--sf);border:1px solid var(--br);border-radius:8px;padding:36px;backdrop-filter:blur(20px)}
    .fl{display:block;font-size:.7rem;color:var(--mt);letter-spacing:.1em;text-transform:uppercase;margin-bottom:7px}
    .fi,.fsl,.ft{width:100%;background:rgba(255,255,255,.022);border:1px solid rgba(212,175,55,.11);color:var(--tx);padding:11px 15px;border-radius:3px;font-size:.93rem;font-family:'DM Sans',sans-serif;transition:border-color .2s;outline:none}
    .fi:focus,.fsl:focus,.ft:focus{border-color:var(--g)}.fsl option{background:#090C18}.ft{min-height:108px;resize:vertical;line-height:1.65}
    .fcc{font-size:.7rem;color:var(--mt);text-align:right;margin-top:3px}.fr{margin-bottom:18px}
    .vr{display:flex;gap:9px}.vb{flex:1;padding:9px;background:rgba(255,255,255,.022);border:1px solid rgba(212,175,55,.11);color:var(--mt);border-radius:3px;cursor:pointer;font-family:'DM Sans',sans-serif;font-size:.8rem;transition:all .2s}.vb.on{background:rgba(212,175,55,.09);border-color:var(--g);color:var(--g)}
    .fsb{width:100%;background:linear-gradient(135deg,var(--g),#9A7A0A);color:#000;padding:15px;border-radius:3px;font-size:.98rem;font-weight:700;cursor:pointer;border:none;font-family:'DM Sans',sans-serif;margin-top:6px;transition:all .3s;letter-spacing:.02em}
    .fsb:hover{transform:translateY(-1px);box-shadow:0 6px 38px rgba(212,175,55,.38)}.fsb:disabled{opacity:.32;cursor:not-allowed;transform:none}
    .fn{font-size:.7rem;color:var(--mt);text-align:center;margin-top:14px;line-height:1.65}
    .why{padding:72px 20px;max-width:900px;margin:0 auto;position:relative;z-index:1}
    .why h2{font-family:'Cormorant Garamond',serif;font-size:2rem;text-align:center;margin-bottom:48px}
    .wg{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:18px}
    .wc{background:var(--sf);border:1px solid var(--br);border-radius:8px;padding:28px;transition:border-color .3s}.wc:hover{border-color:rgba(212,175,55,.48)}
    .wi{font-size:1.9rem;margin-bottom:14px}.wc h3{font-family:'Cormorant Garamond',serif;font-size:1.2rem;margin-bottom:9px;color:var(--g)}.wc p{color:var(--mt);font-size:.85rem;line-height:1.75}
    .trt{display:flex;gap:24px;justify-content:center;align-items:center;padding:32px 20px;border-top:1px solid var(--br);position:relative;z-index:1;flex-wrap:wrap}
    .ti{display:flex;align-items:center;gap:7px;color:var(--mt);font-size:.78rem}.td{width:5px;height:5px;background:var(--g);border-radius:50%}
    .ov{position:fixed;inset:0;background:rgba(0,0,0,.87);z-index:200;display:flex;align-items:center;justify-content:center;padding:20px;backdrop-filter:blur(10px)}
    .mod{background:#090C18;border:1px solid var(--br);border-radius:12px;padding:44px 36px;max-width:420px;width:100%;text-align:center;animation:si .28s ease}
    .mod h2{font-family:'Cormorant Garamond',serif;font-size:1.8rem;margin-bottom:12px}.mod p{color:var(--mt);line-height:1.7;margin-bottom:24px}
    .pb{font-family:'Cormorant Garamond',serif;font-size:4rem;font-weight:700;color:var(--g);display:block;margin:10px 0 22px}
    .mp{width:100%;background:linear-gradient(135deg,var(--g),#9A7A0A);color:#000;padding:15px;border-radius:3px;font-size:1rem;font-weight:700;cursor:pointer;border:none;font-family:'DM Sans',sans-serif;margin-bottom:11px;transition:all .3s}.mp:hover{transform:translateY(-1px);box-shadow:0 5px 36px rgba(212,175,55,.38)}
    .mc{background:none;border:none;color:var(--mt);cursor:pointer;font-family:'DM Sans',sans-serif;font-size:.8rem;text-decoration:underline}
    .sic{font-size:3.2rem;margin-bottom:18px;animation:pu 1.5s ease infinite}
    .sbs{display:flex;flex-wrap:wrap;justify-content:center;gap:8px;margin-top:18px}
    .sb{display:inline-flex;align-items:center;gap:6px;padding:10px 16px;border-radius:4px;cursor:pointer;font-family:'DM Sans',sans-serif;font-size:.82rem;font-weight:500;border:1px solid var(--br);color:var(--tx);background:var(--sf);transition:all .2s;text-decoration:none}
    .sb:hover{border-color:var(--g);color:var(--g)}.sb.cp{border-color:var(--g);background:rgba(212,175,55,.09);color:var(--g)}
    footer{text-align:center;padding:28px 20px;color:var(--mt);font-size:.72rem;border-top:1px solid var(--br);position:relative;z-index:1;letter-spacing:.05em}
    @keyframes fu{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}
    @keyframes si{from{opacity:0;transform:scale(.94)}to{opacity:1;transform:scale(1)}}
    @keyframes pu{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}
    .rtl{direction:rtl;text-align:right}.rtl .fcc{text-align:left}
    @media(max-width:600px){nav{padding:12px 14px}.lbs{max-width:65%}.mod{padding:28px 18px}.fc{padding:22px 16px}.cds{display:none}}
  `}</style>
  <Stars/>
  <nav>
    <div className="nlo">OneMessage.world</div>
    <div className="lbs">{Object.entries(T).map(([k,v])=><button key={k} className={`lb${lang===k?" on":""}`} onClick={()=>setLang(k)}>{v.cta_lang}</button>)}</div>
  </nav>

  {/* HERO */}
  <section className={`hero${rtl?" rtl":""}`}>
    <div className="bdg">{t.badge}</div>
    <div className="ht"><span>{t.hero1}</span><span>{t.hero2}</span><span>{t.hero3}</span></div>
    <div className="dv" style={{marginTop:32}}/>
    <p className="hs">{t.sub}</p>
    <div className="cr">
      <div className="ci"><div className="cn">{ac.toLocaleString()}</div><div className="cl">{t.counter_msgs}</div></div>
      <div className="ci"><div className="cn">87</div><div className="cl">{t.counter_countries}</div></div>
      <div className="ci"><div className="cn">${raised.toLocaleString("en",{minimumFractionDigits:2,maximumFractionDigits:2})}</div><div className="cl">{t.counter_raised}</div></div>
    </div>
    <button className="cb" onClick={goForm}>{t.cta}</button>
    <p className="cs">🔒 {t.cta_sub}</p>
  </section>

  {/* STORY */}
  <section className={`story${rtl?" rtl":""}`}>
    <div className="sbdg">{t.story_badge}</div>
    <h2>{t.story_title}</h2>
    <p>{t.story_p1}</p><p>{t.story_p2}</p><p>{t.story_p3}</p>
    <blockquote>{t.story_quote}</blockquote>
  </section>

  {/* LIVE FEED */}
  <section className={`live${rtl?" rtl":""}`}>
    <h3>🟢 {t.live_title}</h3>
    <div className="lfg">{feed.map((m,i)=><div key={i} className="lfc"><span style={{fontSize:"1.3rem"}}>{m.f}</span><div className="lfi"><div className="lfn">{m.n}</div><div className="lft">{m.t} ago</div></div><div className="lfd"/></div>)}</div>
  </section>

  {/* TRANSPARENCY */}
  <section className={`trans${rtl?" rtl":""}`}>
    <h3>📊 {t.transparency}</h3>
    <div className="tg">
      <div className="tc"><div className="tn">{count.toLocaleString()}</div><div className="tl">{t.counter_msgs}</div></div>
      <div className="tc"><div className="tn">${raised.toLocaleString("en",{minimumFractionDigits:2})}</div><div className="tl">{t.counter_raised}</div></div>
      <div className="tc"><div className="tn">87</div><div className="tl">{t.counter_countries}</div></div>
      <div className="tc"><div className="tn" style={{fontSize:"1.5rem",lineHeight:1.3}}>Jan 1<br/>2036</div><div className="tl" style={{marginTop:8}}>Opening date</div></div>
    </div>
  </section>

  {/* COUNTDOWN */}
  <section className={`cd${rtl?" rtl":""}`}>
    <h3>{t.cd_title}</h3>
    <div className="cdg">
      <div className="cdi"><div className="cdn">{String(cd.d).padStart(4,"0")}</div><div className="cdl">{t.days}</div></div>
      <div className="cds">·</div>
      <div className="cdi"><div className="cdn">{String(cd.h).padStart(2,"0")}</div><div className="cdl">{t.hours}</div></div>
      <div className="cds">·</div>
      <div className="cdi"><div className="cdn">{String(cd.m).padStart(2,"0")}</div><div className="cdl">{t.mins}</div></div>
      <div className="cds">·</div>
      <div className="cdi"><div className="cdn">{String(cd.s).padStart(2,"0")}</div><div className="cdl">{t.secs}</div></div>
    </div>
  </section>

  {/* FORM */}
  <section ref={formRef} className={`fsec${rtl?" rtl":""}`}>
    <h2>{t.form_title}</h2>
    <div className="fc">
      <div className="fr"><label className="fl">{t.form_name}</label><input className="fi" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="..."/></div>
      <div className="fr"><label className="fl">{t.form_country}</label><select className="fsl" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}><option value="">—</option>{COUNTRIES.map(c=><option key={c} value={c}>{c}</option>)}</select></div>
      <div className="fr"><label className="fl">{t.form_msg}</label><textarea className="ft" maxLength={MAX} value={form.msg} onChange={e=>setForm({...form,msg:e.target.value})} placeholder={t.form_msg}/><div className="fcc">{MAX-form.msg.length} {t.form_chars}</div></div>
      <div className="fr"><label className="fl">{t.form_vis}</label><div className="vr"><button className={`vb${form.vis==="public"?" on":""}`} onClick={()=>setForm({...form,vis:"public"})}>{t.form_public}</button><button className={`vb${form.vis==="private"?" on":""}`} onClick={()=>setForm({...form,vis:"private"})}>{t.form_private}</button></div></div>
      <button className="fsb" disabled={!form.msg.trim()} onClick={()=>setModal(true)}>{t.form_submit}</button>
      <p className="fn">🔐 {t.form_note}</p>
    </div>
  </section>

  {/* WHY */}
  <section className={`why${rtl?" rtl":""}`}>
    <h2>{t.why_title}</h2>
    <div className="wg">
      <div className="wc"><div className="wi">🕯️</div><h3>{t.why1_t}</h3><p>{t.why1_d}</p></div>
      <div className="wc"><div className="wi">💰</div><h3>{t.why2_t}</h3><p>{t.why2_d}</p></div>
      <div className="wc"><div className="wi">⏳</div><h3>{t.why3_t}</h3><p>{t.why3_d}</p></div>
    </div>
  </section>

  <div className="trt"><div className="ti"><div className="td"/>{t.trust1}</div><div className="ti"><div className="td"/>{t.trust2}</div><div className="ti"><div className="td"/>{t.trust3}</div></div>
  <footer>{t.footer}<span style={{margin:"0 10px",opacity:.4}}>·</span><Link href="/legal" style={{color:"var(--mt)",textDecoration:"underline",textUnderlineOffset:3}}>Terms of Service</Link><span style={{margin:"0 10px",opacity:.4}}>·</span><Link href="/legal" style={{color:"var(--mt)",textDecoration:"underline",textUnderlineOffset:3}}>Privacy Policy</Link></footer>

  {modal&&<div className="ov" onClick={e=>{if(e.target===e.currentTarget){setModal(false);setAgreed(false);}}}><div className="mod"><span className="pb">$1</span><h2>{t.modal_title}</h2><p>{t.modal_body}</p><label style={{display:"flex",alignItems:"flex-start",gap:10,cursor:"pointer",margin:"16px 0",textAlign:"left"}}><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} style={{marginTop:3,accentColor:"#D4AF37",flexShrink:0,width:15,height:15}}/><span style={{fontSize:".78rem",color:"var(--mt)",lineHeight:1.55}}>I agree to the <Link href="/legal" target="_blank" style={{color:"#D4AF37"}}>Terms of Service</Link> and understand payments are non-refundable.</span></label><button className="mp" onClick={pay} disabled={!agreed} style={{opacity:agreed?1:.4,cursor:agreed?"pointer":"not-allowed"}}>{t.modal_pay}</button><br/><button className="mc" onClick={()=>{setModal(false);setAgreed(false);}}>{t.modal_cancel}</button></div></div>}

  {success&&<div className="ov"><div className="mod"><div className="sic">✉️</div><h2>{t.success_title}</h2><p>{t.success_sub}</p><p style={{fontSize:".82rem",color:"var(--mt)",marginTop:18}}>{t.success_share}</p><div className="sbs"><a className="sb" href={`https://twitter.com/intent/tweet?text=${st()}`} target="_blank" rel="noreferrer">🐦 {t.share_tw}</a><a className="sb" href={`https://wa.me/?text=${st()}`} target="_blank" rel="noreferrer">💬 {t.share_wa}</a><a className="sb" href={`https://www.facebook.com/sharer/sharer.php?u=https://onemessage.world`} target="_blank" rel="noreferrer">👤 {t.share_fb}</a><button className={`sb${copied?" cp":""}`} onClick={cpLink}>🔗 {copied?t.copied:t.share_copy}</button></div></div></div>}
  </>);
}
